{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anvil.fullname" $ }}-{{ $name }}
  labels:
    {{- include "anvil.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      {{- include "anvil.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "anvil.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      serviceAccountName: {{ include "anvil.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}/{{ $name }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $app.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ $.Values.global.environment }}
            - name: PORT
              value: "{{ $app.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "anvil.fullname" $ }}-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "anvil.fullname" $ }}-secrets
                  key: redis-url
            - name: NEXTAUTH_URL
              value: "https://{{ $.Values.global.domain }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml (default (dict "requests" (dict "memory" "128Mi" "cpu" "50m") "limits" (dict "memory" "512Mi" "cpu" "500m")) $app.resources) | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
